### PR TITLE
Fix typo in a comment in mathmodel.ipynb

### PR DESCRIPTION
**Pull request by quackduck**
Just a small change - "figyre" to "figure"!

### CODE REVIEW

**Review by aatishb — APPROVED** [review]

**Comment by aatishb** [comment]
@quackduck thanks!

**Comment by aatishb** [comment]
@all-contributors add @quackduck for doc

**Comment by aatishb** [comment]
I like to err on the side of being inclusive with credit :) but let me know if you'd prefer to not be listed.

**Comment by quackduck** [comment]
Haha, thanks!

**Comment by quackduck** [comment]
Hey, @aatishb I just noticed a grammar issue and I fixed it over on the branch I'd made on my fork. It isn't showing up here though. Is it because the PR is closed?

**Comment by aatishb** [comment]
Thanks! I think that's right, try opening up a new PR for this?

**Comment by quackduck** [comment]
I opened one up. The old commit still shows. Should I delete it? Or do we just resolve the merge conflicts when they appear? Or will they not appear because both have the same content?

Also, is there no way to reopen a PR?

**Comment by aatishb** [comment]
It's strange that the old commit shows, In any case we can deal with it on merging.
You can't reopen a merged PR, the best you can do is create a new PR that undoes the first one (i.e. revert a PR), which isn't what we want here.

**Pull request merged**
