### PR TITLE
Serbian Translation

### PR DESCRIPTION
**Pull request by Mentathiel**
Hi, this is my attempt at a Serbian translation. I think it's mostly pretty good, but I will revise if I get some second opinions to the contrary. Anyone who speaks Serbian is welcome to help along, either by sending me suggestions or editing the translation themselves.

Note that illustrations saying "Contagious Person" and "Susceptible Person" couldn't be translated in html, so I left them as is. If somebody knows how to fix that, translations should be:
- Contagious Person = Zarazna osoba
- Susceptible Person = Podložna osoba

### CODE REVIEW

**Comment by aatishb** [comment]
I'm so sorry that this slipped by me! My apologies. I will follow up on this today.

**Review by aatishb — APPROVED** [review]

**Comment by aatishb** [comment]
@allcontributors add @Mentathiel for translation

**Comment by aatishb** [comment]
@Mentathiel merged. Thank you for your contribution and I'm so sorry for the delay.

**Comment by aatishb** [comment]
Tagging #4

**Comment by Mentathiel** [comment]
@aatishb Hey, I'm only seeing this now, thanks for the merge! No worries about the delay. :)

**Pull request merged**
