### PR TITLE
Programmatically generate links to different translation pages.

### PR DESCRIPTION
**Pull request by professor-k**
As we spoke earlier. Now all links are created based on list located in vue-definitions.js. I had no previous experience with vue.js, but I guess I figured it out. Wasn't much of smooth ride, to be fair 😄

### CODE REVIEW

**Comment by aatishb** [comment]
@professor-k great, thanks for this! This looks like a good approach. I'll test and might make few stylistic changes to this, if that's all right.

**Comment by aatishb** [comment]
@all-contributors add @professor-k for code

**Comment by aatishb** [comment]
@professor-k thanks for your work on this! merged.

**Comment by professor-k** [comment]
@aatishb I looked into your changes, and got humbled. But at least I learned few new tricks about vue.js. I'll Thank you 😃

**Comment by aatishb** [comment]
@professor-k 👍 Was happy to build on your work! Thanks for taking the initiative. :) The only non-stylistic addition was I thought a list would be better for accessibility -- and happily this also fixed a layout bug in Hebrew. The other changes were all stylistic preferences (i.e. encapsulating all the messy details into the component so the html is as simple as possible.).

**Pull request merged**
