### PR TITLE
Italian Translation

### PR DESCRIPTION
**Pull request by albannabla**
Hi, I have reviewed the text a few times after translating and it should now be quite accurate, but a few animations and graphs are still in English, as per already reported in the comments. Hope this helps!

### CODE REVIEW

**Comment by aatishb** [comment]
Excellent, thanks for this! I'll go ahead and merge in the new changes and let you know the remaining steps.

**Comment by aatishb** [comment]
Hi @albannabla, Thanks again for all your work on this. I brought this closer to the main branch. Here are the remaining things to do:

- [ ] In the header of `index.html`, `index-fr.html`, `index-he.html`, `index-it.html`, translate the link 'Italian' into Italian :)
- [ ] In the header of `index-it.html`, translate the word 'by'
- [ ] In `index-it.html`, translate Contagious Person and Susceptible Person for all four routes
- [ ] In `index-it.html`, translate graph titles and annotations for both graphs
- [ ] (optional) Add a line of credit to yourself as described in the (recently edited) instructions here: https://github.com/aatishb/maskmath/issues/4

Let me know when you're done, and I'll proceed to review & merge.

**Comment by albannabla** [comment]
Hi @aatishb, I have done all above. I am not sure why, though, my "page" preview only shows the credit section in the Italian version... I hope I did not mess up anything, please will you review and let me know if you need any more help from me.

thank you!

**Comment by aatishb** [comment]
Puzzling! I did some digging and I found that [this commit](https://github.com/aatishb/maskmath/pull/12/commits/efe1032b99c6dc9ad71183e6e98745fef66d465f) (efe1032) is the first one that breaks the layout. I'm not sure what went wrong as yet, investigating this.

**Comment by aatishb** [comment]
I think I got it.. it's totally not your fault by the way, as you couldn't have known this would be an issue! [This line](https://github.com/aatishb/maskmath/pull/12/commits/efe1032b99c6dc9ad71183e6e98745fef66d465f#diff-aa08f48db4d25e130756ea8b6cfcf79aR610) contains a single quote, which causes the code to break. Weirdly, it's not providing an error message which is why it's so hard to catch, so that's something I'll look into later. For now this is an easy fix.

**Review by aatishb — APPROVED** [review]

**Comment by aatishb** [comment]
@all-contributors add @albannabla for translation

**Comment by aatishb** [comment]
@albannabla all done, thanks for your great work on this!

**Pull request merged**
