### PR TITLE
Ukrainian translation

### PR DESCRIPTION
**Pull request by professor-k**
Hello Aatish,

Here is Ukrainian translation for your consideration.

Also, I took liberty of embedding Ukrainian dubbed version of companion video instead of original. It is made by local pop-science channel, and that's actually where I first saw the reference to your essay. Respectively, I added them to the credits section as well, preserving the original part, of course. Links to Wikipedia were also adjusted to point to Ukrainian articles. 

Hope that's okay. If not, I'll fix it back as it was.

Thanks,
Great essay, by the way. Hope it saves some lives.

### CODE REVIEW

**Comment by aatishb** [comment]
Hi, thanks for your efforts on this. For copyright reasons & since this essay was a collaboration with Minute Physics, I'd prefer to maintain the link to the video as is. You can just commit the change to your branch and it should show up here. (As a side note, I believe it's possible to contribute Ukranian subtitles to the video, but let's keep that separate from this translation.)
When you're done, I'll work on bringing this in sync with the live branch, and will let you know if any steps remain.

**Comment by professor-k** [comment]
You are the boss. Done.

**Comment by professor-k** [comment]
I was also thinking of creating some kind of javascript file to generate language links in single place (as html doesn't support any reasonable kind of snippet embedding). Merging those four translation pull requests together will be annoying to say the least. I can spend half an hour sometime in the evening if you're interested.

**Comment by aatishb** [comment]
@professor-k thanks for working on this! I'll proceed to merge the live branch into your branch and resolve conflicts. Will keep you posted.

**Comment by aatishb** [comment]
@professor-k Thanks for your efforts on this! I have merged it and it's now live. 

Re: automatic the header links, I think this is worth trying out as the current manual process is starting to get quite unwieldy. Let's move this to a new issue. Are you familiar with vue.js? I am already using this for the interactive on this page, and I think we could use something like [v-for](https://vuejs.org/v2/guide/list.html) to iterate though a list of translations.

**Comment by aatishb** [comment]
@all-contributors add @professor-k for translation

**Comment by aatishb** [comment]
tagging #4

**Pull request merged**
