### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by fbuters**
Hi there!
This is the first draft of the Dutch translation. Any/all feedback is welcome!

Cheers, 
Frank

### CODE REVIEW

**Comment by aatishb** [comment]
@fbuters Here are a couple of things remaining before we publish this:

- [ ] Translate `% Infected` in the last graph
- [ ] Translate `Click to Expand` in second dropdown box
- [ ] (Optional) Add a line of credit & link to yourself in the credits as suggested [here](https://github.com/aatishb/maskmath/issues/4) :)
- [ ] In vue-definitions.js, to be consistent with other languages, the language name listed should be whatever the name is in the language itself (i.e. the native name for the language). So would `Nederlands` be correct here?

You can make these changes as before in your branch, and they will automatically show up here once saved. Alternatively, you can reply with the remaining translations and I'll put them in. Thanks!

**Comment by aatishb** [comment]
Tagging #4

**Comment by fbuters** [comment]
Hey @aatishb, sure no problem, I will have a look later today! 

Cheers, 
Frank

**Review by aatishb — APPROVED** [review]

**Comment by aatishb** [comment]
@all-contributors add @fbuters for translation

**Comment by aatishb** [comment]
@fbuters Thanks for all your work on this, Frank! It's now live. :)

**Pull request merged**
