### PR TITLE
Catalan translation

### PR DESCRIPTION
**Pull request by dvirgili**
This is the first attempt of translation into catalan
(thanks for the contributor's guide!)

### CODE REVIEW

**Comment by aatishb** [comment]
Hi @dvirgili. Thanks for submitting this translation. If you're done with it, I'll go ahead and get this in sync with the latest version of the website and will let you know if any small tasks remain.

**Comment by aatishb** [comment]
Tagging #4

**Comment by dvirgili** [comment]
> 
> 
> Hi @dvirgili. Thanks for submitting this translation. If you're done with it, I'll go ahead and get this in sync with the latest version of the website and will let you know if any small tasks remain.

Thank you very much for your work, this seems really useful to me. I made some small corrections and asked for a merge again with the base branch, this last one seems to be correct to me.

**Review by aatishb — APPROVED** [review]

**Comment by aatishb** [comment]
@dvirgili Apologies for dragging my feet on this. I just merged this, it's now live. Thank you so much for your thorough work on this! :)

**Comment by aatishb** [comment]
@all-contributors add @dvirgili for translation

**Pull request merged**
