### PR TITLE
Brazilian Portuguese Translation

### PR DESCRIPTION
**Pull request by gnegrelligarcia**
Hello! This is a first pass at a Brazilian Portuguese Translation :)

### CODE REVIEW

**Comment by aatishb** [comment]
Thanks for this! I'll merge the most recent changes from the live branch into this pull request, and then will send you a list of remaining steps.

**Comment by aatishb** [comment]
Hi @gnegrelligarcia, Thanks again for all your work on this. I brought this closer to the main branch. Here are the remaining things to do:

- [ ] In the header of `index.html`, `index-fr.html`, `index-he.html`, `index-it.html`, `index-pt.html`, translate the link 'Brazilian Portugese' into Brazilian Portugese :)
- [ ] In the header of `index-pt.html`, translate the word 'by'
- [ ] In `index-pt.html`, translate Contagious Person and Susceptible Person for all four routes
- [ ] In `index-pt.html`, translate graph titles and annotations for both graphs (if you happen to use a single quote within the titles or annotations, you have to put a backslash before it like this `\'` )

Let me know when you're done, and I'll proceed to review & merge. 

I believe you can make these changes simply by committing to your branch as before, and they should show automatically up here. If for some reason this becomes complicated or doesn't work, just let me know, I can also take care of the changes if you send me the translations!

**Comment by aatishb** [comment]
Tagging https://github.com/aatishb/maskmath/issues/4

**Comment by gnegrelligarcia** [comment]
Hi Aatish!

I just noticed that I cannot edit the "% Infected" in the "How Masks Reduce Infections" graph. I know this is just a detail, but you know :P

**Comment by aatishb** [comment]
Thanks for this, reviewing now!

**Review by aatishb — APPROVED** [review]

**Comment by aatishb** [comment]
@all-contributors add @gnegrelligarcia for translation

**Comment by aatishb** [comment]
@gnegrelligarcia Thanks for your great work on this! I've merged the changed and it's live. You can now safely delete your fork if needed. 

Good point about the graph hover text not being translated. I missed that, but it should be a fairly straightforward fix. You're welcome to open an issue for it, as a reminder for me or anyone else to investigate it. :)

**Comment by gnegrelligarcia** [comment]
Yaay! Thanks for the update :)
If I can help any further, please let me know! It was a lot of fun
translating the essay!

**Comment by DeepSpace2** [comment]
@aatishb @gnegrelligarcia I've created a PR that allows translating the graph hover label (#20). I didn't bother making the other graph's hover label translateable because it only says `R0`, which I assume will stay the same in all languages, but if needed it is very easy to make translatable as well.

**Comment by aatishb** [comment]
@DeepSpace2 amazing, thanks!

**Pull request merged**
