### PR TITLE
Changed 'graph3Traces' to a method and enabling translation of graph hover label

### PR DESCRIPTION
**Pull request by DeepSpace2**
Changed `graph3Traces` to a method and enabled translation of graph hover label. In this PR I translated only the Hebrew version, and used the English term ('% infected') as the default value for other languages

### CODE REVIEW

**Comment by aatishb** [comment]
Hi @DeepSpace2, thanks for this! I took a quick look & like this approach. Here are my initial thoughts:

1. I would suggest explicitly passing the '% Infected' text to the method, rather than have it be a default value, i.e. `graph3Traces('% Infected')` This way when people are translating, they will know they should also translate that text. 

2. Stylistically, it may also slightly help for the text being passed to be on its own line so it's clearer to translators that it should be translated? Just a thought.

**Comment by DeepSpace2** [comment]
@aatishb Sure, done :)

**Review by aatishb — APPROVED** [review]

**Comment by aatishb** [comment]
@DeepSpace2 thanks for this clean fix!
@all-contributors add @DeepSpace2 for code
@all-contributors add @gnegrelligarcia for bug
@gnegrelligarcia you're welcome to translate the '% infected' by committing the change on [this page](https://github.com/aatishb/maskmath/edit/master/index-pt.html) (which will open a PR)

**Comment by aatishb** [comment]
@all-contributors add @DeepSpace2 for code

**Comment by aatishb** [comment]
@all-contributors add @gnegrelligarcia for bug

**Pull request merged**
