### PR TITLE
Russian translation of the essay

### PR DESCRIPTION
**Pull request by ulkar-aghayeva**
Hi there,

This is a first pass Russian translation. I have a couple of questions: 

- In Russian, there’s a difference between “You” and “thou”, with the former being more formal. In the current version, I chose the “thou” version, as it feels like addressing one’s peers, but please let me know if you prefer the more formal address.
- Should I leave the English names (like people’s names) in the original spelling, or should I transliterate them into Russian characters?

I will go through my translation once again, but if there are any Russian speakers out there who could read it through and watch out for typos or inexact translations, please let me know!

My best,
Ulkar (she/her)

### CODE REVIEW

**Comment by aatishb** [comment]
@ulkar-aghayeva thank you so much for this!

Re: the difference between the two you's, I agree with your judgement on adopting the more informal tone for one's peers, that would be my preferred tone as well. 

Out of curiosity, would the informal 'you' sounds less respectful to readers? The reason I ask is Hindi also has multiple 'you' words, and the informal one is typically consider disrespectful for people you don't know.

I would say use the original English spelling for names, as this would be consistent with other translations, but let me know if you think it's better to transliterate.

**Comment by aatishb** [comment]
@ulkar-aghayeva I'll work on bringing this in sync with the current version of the website, and once I'm done will send you a list of the remaining steps.

**Comment by aatishb** [comment]
Hi @ulkar-aghayeva, Thanks again for all your work on this! I brought this in sync with the current version of the website. The only remaining task is:

- [ ] In second graph component, translate the '% Infected' hover text to Russian (line 608)

You can commit the change on your fork and it should automatically appear here.

Other than that, I noticed you already transliterated some of the names, and I'm open to your thoughts on this. My tentative thoughts are if it's a tradeoff between being understood by more people vs. consistency, let's err towards being more readable & widely understood.

Tagging https://github.com/aatishb/maskmath/issues/4

**Comment by ulkar-aghayeva** [comment]
Hi @aatishb, Sure, I'll add that translation - I somehow missed it.

Re: you's - I've thought about it, and it seems to me that using the formal
you would actually be safer. It may sound a bit didactic, but it is always
used in official public announcements - and in many educational youtube
videos. In general, the informal you is used with peers and younger people
(whether you know them or see them for the first time), and it would be
perceived as offensive if used with older people. So if an elder person
reads the essay with an informal you, it might sound off to them. I think
it's better if I change the pronoun in my translation. When I read the
essay in English, I read it as if it were written with an informal you
addressed to me, but in Russian it's a bit different.

And re: transliterations - I did at first transliterate a couple of names,
but then thought it would be more difficult to find people's work if their
names are written in Russian characters.

I'll now go over the translation, do the proofreading and make all these
changes and commit them.

My best,
Ulkar

**Comment by aatishb** [comment]
Hi @ulkar-aghayeva, you didn't miss that line, it's a new addition from https://github.com/aatishb/maskmath/pull/20 that I merged in here :)

re: you's and transliteration, your reasoning sounds good to me. Thanks for thinking this through.

When you're done with changes on your end (no hurry), let me know, and I'll proceed to publish this (unless someone volunteers to review it first).

Cheers,
Aatish

**Comment by ulkar-aghayeva** [comment]
Hi @aatishb, I've just finished editing my translation - I think it's good
to go now. Many thanks for your brilliant work!

My best,
Ulkar

**Comment by aatishb** [comment]
Thanks @ulkar-aghayeva!

I took a close look and there a few quick steps remaining:

- [ ]  Translate 'by' in the header (Line 46)
- [ ]  Translate 'Mask Usage in Line 252 and Line 354

Other than that it looks ready to go.

**Comment by ulkar-aghayeva** [comment]
Hi @aatishb,

Just added those missing parts.

My best,
Ulkar

**Comment by aatishb** [comment]
@ulkar-aghayeva could you also translate the 'Credits and References' heading? Or just let me know the translation and I can make the edit. Apologies for the add-on request, I missed this earlier.

**Comment by ulkar-aghayeva** [comment]
@aatishb sorry I missed it too! Now added.

**Review by aatishb — APPROVED** [review]

**Comment by aatishb** [comment]
@all-contributors add @ulkar-aghayeva for translation

**Comment by aatishb** [comment]
@ulkar-aghayeva merged! Thanks so much for your efforts on this! :)

**Pull request merged**
