### PR TITLE
Constant width dotted spans (%s that respond to sliders)

### PR DESCRIPTION
**Pull request by unfamiliarplace**

### CODE REVIEW

**Comment by aatishb** [comment]
Hi @unfamiliarplace, Thanks for submitting this, I took a look. 

I like the simple fix but a couple of issues come up: 1. the dotted line extends wider than the numbers (i.e. we're trading off one aesthetic issue for another), and 2. in the R0 section it seems to break things with the text because the dotted line is used for other purposes. 

It seems a way to fix this would be to wrap the numbers in a fixed-width div, rather than altering the dotted line span. However this would involved changing these components across multiple index.html files (as we have translations coming in).

Personally I'm not sure it's worth the effort if the fix involves many little html changes, but let me know if you feel strongly otherwise and/or would like to take this on! Alternatively if there's an easy fix that doesn't involved many html changes we could try that.

**Comment by unfamiliarplace** [comment]
(a) Yeah, agreed that it's a tradeoff. I think it's still better than wriggling, though :)

(b) Good catch. Since it's just the one place it's broken in R0, we might as well cheat by hardcoding it. I'll commit this change:

```
div:not(.splash) > span.dotted, span > span.dotted {
  display: inline-block;
  width: 2em;  
}
```

What makes the hardcoding less of a sin IMO is that it'll only be outdated if the HTML changes, and if you need to do that you could just add a `.constant-width` class while you're at it.

**Comment by unfamiliarplace** [comment]
Oh, hang on, I misread issue (a) -- you're wondering if we can avoid extending the dotted line, and just have blank space for the extra width. I'll try some hackish things and get back to you...

**Comment by unfamiliarplace** [comment]
OK, wrapped the spans in constant width divs using JS (just stuck it into lambertw.js to avoid updating the HTML, lol). The CSS now targets that div instead. So the previous commit solves just issue b, whereas this commit solves both, at the expense of a little code pollution... :)

**Pull request closed without merging**
