### PR TITLE
Fixing empty space on page on Firefox due to dir='rtl' on Hebrew translation.

### LINKED ISSUE #24: Issue with Page Width on Hebrew Translation
On the [Hebrew translation](https://aatishb.com/maskmath/index-he.html), it's possible to scroll left to a large blank space on the left side of the page. If I remove the `dir="rtl"` from the body tag (which indicates that text is read right to left), this seems to fix the issue. I don't understand the cause for the bug, but maybe making this change and adding `dir="rtl"` to the children div of `<body>` instead will fix it?

cc @DeepSpace2

### PR DESCRIPTION
**Pull request by DeepSpace2**
Closes #24

### CODE REVIEW

**Comment by DeepSpace2** [comment]
You may want to squash these commits when merging to clean up my mess... sorry about that, I messed up the update from upstream ;)

**Comment by aatishb** [comment]
Thanks for this @DeepSpace2!

One small thing I noticed that I missed earlier, we are missing the headings corresponding to 'Say it Don't Spray it", and 'Maskology'. Do you think there's some phrase we can use for the translation that conveys a similar meaning?

**Comment by DeepSpace2** [comment]
@aatishb I originally opted to not translate these headers because it felt a bit "artificial" and un-natural. If you are ok with that I think we can leave it as it is. If you think these headers are important I'll translate them in the way I think is the best.

**Comment by aatishb** [comment]
Sure, let's leave it as is.

**Pull request merged**
