### PR TITLE
Korean translation

### PR DESCRIPTION
**Pull request by dev-owner**
translate KR version

### CODE REVIEW

**Comment by dev-owner** [comment]
@aatishb When you get a chance, would you review this PR?

**Comment by aatishb** [comment]
Thanks for flagging, this slipped by me! Will review this weekend.
________________________________

**Comment by dev-owner** [comment]
@aatishb, I know you're super busy, but I hope you don’t forget this PR.

**Comment by aatishb** [comment]
Thank you for the reminder, I will review this weekend. Apologies for the delay.
________________________________

**Comment by aatishb** [comment]
Tagging #4

**Comment by aatishb** [comment]
@all-contributors add @dev-owner for translation

**Comment by aatishb** [comment]
@dev-owner thank you for this thorough translation and for your patience! I've merged it and added you to the contributor list. Really appreciate your input.

**Pull request merged**
